GA: Always install 'et_EE.utf8'

diff --git a/.github/workflows/check-cli-javascript.yml b/.github/workflows/check-cli-javascript.yml
--- a/.github/workflows/check-cli-javascript.yml
+++ b/.github/workflows/check-cli-javascript.yml
@@ -29,16 +29,11 @@ jobs:
       LC_COLLATE: ${{ matrix.config.language }}
 
     steps:
-    - name: Assert LANGUAGE availability
+    - name: Assert LANGUAGE availabilities
+      if: runner.os == 'Linux'
       run: |
-        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
-        if [[ -n ${LANGUAGE} ]]; then
-            if ! locale -a | grep "${LANGUAGE}"; then
-                sudo apt-get update && sudo apt-get install tzdata locales -y
-                sudo locale-gen "${LANGUAGE}"
-            fi
-            locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
-        fi
+        sudo locale-gen et_EE.utf8
+        locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
         
     - uses: actions/checkout@v4
 
