Assert LANGUAGE is available - all jobs

diff --git a/.github/workflows/check-cli-javascript.yml b/.github/workflows/check-cli-javascript.yml
--- a/.github/workflows/check-cli-javascript.yml
+++ b/.github/workflows/check-cli-javascript.yml
@@ -29,6 +29,13 @@ jobs:
       LC_COLLATE: ${{ matrix.config.language }}
 
     steps:
+    - name: Assert LANGUAGE availability
+      run: |
+        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
+        if [[ -n ${LANGUAGE} ]]; then
+            locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
+        fi
+        
     - uses: actions/checkout@v4
 
     - name: Use Node.js ${{ matrix.config.node }}
diff --git a/.github/workflows/check-cli-python.yml b/.github/workflows/check-cli-python.yml
--- a/.github/workflows/check-cli-python.yml
+++ b/.github/workflows/check-cli-python.yml
@@ -43,6 +43,13 @@ jobs:
       LC_COLLATE: ${{ matrix.config.language }}
       
     steps:
+    - name: Assert LANGUAGE availability
+      run: |
+        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
+        if [[ -n ${LANGUAGE} ]]; then
+            locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
+        fi
+        
     - uses: actions/checkout@v4
 
     - name: Set up Python
@@ -68,13 +75,6 @@ jobs:
         echo "LANGUAGE: ${LANGUAGE:-<not set>}"
         echo "LC_COLLATE: ${LC_COLLATE:-<not set>}"
 
-    - name: Assert LANGUAGE availability
-      run: |
-        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
-        if [[ -n ${LANGUAGE} ]]; then
-            locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
-        fi
-        
     - name: Check CLI
       if: runner.os != 'Windows'
       run: make check-cli/seguid-python
diff --git a/.github/workflows/check-cli-r.yml b/.github/workflows/check-cli-r.yml
--- a/.github/workflows/check-cli-r.yml
+++ b/.github/workflows/check-cli-r.yml
@@ -42,6 +42,13 @@ jobs:
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
       
     steps:
+    - name: Assert LANGUAGE availability
+      run: |
+        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
+        if [[ -n ${LANGUAGE} ]]; then
+            locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
+        fi
+        
       - uses: actions/checkout@v4
 
       - uses: r-lib/actions/setup-r@v2
